### ISSUE TITLE
M_PI and M_PI_2 constants missing

### ISSUE THREAD

**Issue by brucelane** [bakercp/ofxGeo#3]
hi, 
I added : 
		const double  M_PI = 3.14159265358979323846;
		const double  M_PI_2 = 6.283185307179586476925286766559;
to GeoUtils.cpp to compile without errors

**Comment by bakercp** [comment]
Strange -- it should have been pulling those from the math headers.  I just updated it to just use the openFrameworks constants.

**Comment by bakercp** [comment]
Should be fixed by https://github.com/bakercp/ofxGeo/commit/a6ebfd369a368bb56d386eed4aebd597c68d3f8e.
