### ISSUE TITLE
clang warnings

### ISSUE THREAD

**Issue by danomatika** [bakercp/ofxGeo#5]
clang is throwing a number of "shifting negative sign is undefined" warnings when building GeodesicExactC4.cpp. Seems like one of those "works in C, warnings in C++" situation as per http://stackoverflow.com/questions/35805837/gcc-and-clang-produce-different-outputs-while-left-shifting-with-unsigned-values

Anyway, I believe the best solution is to tell clang to ignore that specific warning in the addon_config.mk ADDON_CFLAGS for OS X & iOS ala:

    ADDON_CFLAGS += -Wshift-negative-value

**Comment by bakercp** [comment]
Hey, I just updated to the latest versions of everything.  I don't see such warnings on xcode or in linux.  Can you try it with the updated version?

**Comment by danomatika** [comment]
Nope, same deal when building for Debug.

<img width="245" alt="screen shot 2016-04-15 at 11 34 27 am" src="https://cloud.githubusercontent.com/assets/480637/14569797/16f46506-02fe-11e6-9998-0d51cf36ac21.png">

**Comment by bakercp** [comment]
Hm.  Well, it's an upstream "problem" :) I'd prefer not ignore warnings ... that said, I can't figure out for the life of me how to report an issue upstream without leaving it on their forum ...

https://sourceforge.net/p/geographiclib/discussion/1026620/

Got any insights?

**Comment by danomatika** [comment]
Click the paper airplane icon to the upper left of the panel.

**Comment by bakercp** [comment]
Just sent a note referencing this issue.

**Comment by cffk** [comment]
Please try applying the attached patch to GeodesicExactC4.cpp and let me know if this eliminates the warnings.  Thanks.
[negative-shift-fix.txt](https://github.com/bakercp/ofxGeo/files/221538/negative-shift-fix.txt)

**Comment by danomatika** [comment]
Yup. That fixes the warnings.

I also agree with fixing warnings whenever possible, although it's never usually this easy with upstream changes. :)

**Comment by bakercp** [comment]
@cffk Thanks for the quick response, patch, and Geographclib!

**Comment by danomatika** [comment]
What version of Xcode are you using? I'm generally up to date and I've noticed a shift toward enabling more and more clang warnings. This is not a bad thing as I've found a number of bugs in Pure Data :)

**Comment by bakercp** [comment]
I'm still on 7.2.1.


---
http://christopherbaker.net

**Comment by danomatika** [comment]
That explains it. I'm on 7.3 with (probably) a slightly newer clang.

**Comment by bakercp** [comment]
(can you send me your patched file or PR @danomatika )

**Comment by cffk** [comment]
A simpler fix (compared to the patch I posted) is

    mv GeodesicExactC4.cpp{,~}
    sed -e 's/real(-/-real(/g' GeodesicExactC4.cpp~ > GeodesicExactC4.cpp

applied to the original GeodesicExactC4.cpp

**Comment by bakercp** [comment]
Fancy. Thanks again sir. It's this something you'll incorporate in a future version?

**Comment by cffk** [comment]
Yes (but I'm not sure when the next version will be released).  For now, either incorporate the changes or suppress the warnings.

**Comment by bakercp** [comment]
Perfect. Thanks @cffk!
